name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: "${{ github.workspace }}/backend"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ---------------- BACKEND ----------------
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      working-directory: backend
      run: python manage.py test

    # ---------------- FRONTEND ----------------
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build
